name: Kirim API Req per 5 Menit

on:
  schedule:
    - cron: */4 * * * *
  push:
    branch: "main"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm ci
    - run: npm test