name: Kirim API Req per 5 Menit

on:
  schedule:
    - cron: '*/4 * * * *'
  push:
    branch: "main"
  
jobs:
  send_req:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} Send API
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4.0.2
      with:
          node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: npm ci
    - run: npm send